<div id="view-content">
	<h3>课程添加</h3>
	<div class="col-md-12">
		<form role="form" class="form form-horizontal" method="post" action="<?php echo $this->baseUrl("/college/colman/add-ok");?>">
			<div class="form-group">
				<label for="college_name">课程名称</label>
				<input type="text" class="form-control" name="college_name" required>
			</div>
			<div class="form-group">
				<label for="dept_code">所属学院</label>
    			<select class="form-control" name="dept_code">
                  <option>1</option>
                </select>
			</div>
			<button type="submit" class="btn btn-primary">提交</button>
		</form>
	</div>
</div>