<div id="view-content">
	<h3>单位列表</h3>
	<div class="col-md-12">
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>序号</th>
                  <th>课程名称</th>
                  <th>所属学院</th>
                </tr>
              </thead>
              <tbody>
              <?php 
              foreach ($this->course_list as $index=>$course) {
                  $index ++;
                  $dept_full_name = $course["course_name"];
                  $dept_name = $course["dept_name"];
                  echo "
		        <tr>
                  <th scope=\"row\">{$index}</th>
                  <td>{$dept_full_name}</td>
                  <td>{$dept_name}</td>
                </tr>";
              }
                ?>
              </tbody>
            </table>
		</div>
		<div>
		<a class="btn btn-success" href="<?php echo $this->baseUrl("/course/couman/add")?>"><i class="glyphicon glyphicon-plus"></i><b>添加</b></a>
		</div>
	</div>
</div>