<div id="view-content">
	<h3>奖学金修改</h3>
	<div class="col-md-12">
		<form role="form" class="form form-horizontal" method="post" action="<?php echo $this->baseUrl("/bursary/info/edit-ok");?>">
			<div class="form-group">
				<label for="college_name">奖学金名称</label>
				<input type="text" class="form-control" name="scholarship_name" value="<?php echo $this->scholarship_info["scholarship_name"];?>" required>
			</div>
			<div class="form-group">
				<label for="college_name">奖学金名额</label>
				<input type="text" class="form-control" name="num" value="<?php echo $this->scholarship_info["num"]?>" required>
			</div>
			<div class="form-group">
				<label for="dept_code">奖学金类型</label>
    			<select class="form-control" name="scholarship_type_code">
    				<option value="">请选择</option>
    				<?php 
    				    $scholarship_type_list = $this->scholar_type_list;
    				    $len = count($scholarship_type_list);
    				    for($i = 0; $i < $len; $i ++) {
    				        $selected = ($scholarship_type_list[$i]["scholarship_type_code"] == $this->scholarship_info["scholarship_type_code"]) ? "selected" : "";
    				        echo "<option value=\"{$scholarship_type_list[$i]["scholarship_type_code"]}\" {$selected}>{$scholarship_type_list[$i]["scholarship_type_name"]}</option>";
    				    }
    				?>
    			</select>
    		</div>
			<div class="form-group">
				<label for="college_name">奖学金学年</label>
				<input type="text" class="form-control" name="scholarship_year" value="<?php echo $this->scholarship_info["scholarship_year"]?>" maxlength="4" required>
			</div>
			<div class="form-group">
				<label for="college_name">开始时间</label>
				<input type="text" class="form-control form_datetime" data-date-format="yyyy-mm-dd" name="start_time" value="<?php echo $this->scholarship_info["start_time"];?>">
			</div>
			<div class="form-group">
				<label for="college_name">结束时间</label>
				<input type="text" class="form-control form_datetime" name="end_time" data-date-format="yyyy-mm-dd" value="<?php echo $this->scholarship_info["end_time"];?>">
			</div>
			<div class="form-group">
				<label for="college_name">是否可见</label>
				<label class="radio-inline">
                  <input type="radio" name="is_visible" id="is_visible0" value="0" <?php echo ($this->scholarship_info["is_visible"] == "0") ? "checked" : "";?>>否
                </label>
                <label class="radio-inline">
                  <input type="radio" name="is_visible" id="is_visible1" value="1" <?php echo ($this->scholarship_info["is_visible"] == "1") ? "checked" : "";?>>是
                </label>
			</div>
			<div class="form-group">
				<label for="college_name">是否开始</label>
				<label class="radio-inline">
                  <input type="radio" name="is_start" id="is_start0" value="0" <?php echo ($this->scholarship_info["is_visible"] == "0") ? "checked" : "";?>>否
                </label>
                <label class="radio-inline">
                  <input type="radio" name="is_start" id="is_start1" value="1" <?php echo ($this->scholarship_info["is_visible"] == "1") ? "checked" : "";?>>是
                </label>
			</div>
			<div class="form-group">
				<label for="college_name">是否过期</label>
				<label class="radio-inline">
                  <input type="radio" name="is_expired" id="is_expired0" value="0" <?php echo ($this->scholarship_info["is_visible"] == "0") ? "checked" : "";?>>否
                </label>
                <label class="radio-inline">
                  <input type="radio" name="is_expired" id="is_expired1" value="1" <?php echo ($this->scholarship_info["is_visible"] == "1") ? "checked" : "";?>>是
                </label>
			</div>
			<div class="form-group">
				<label for="college_name">发放时间</label>
				<input type="text" class="form-control form_datetime" name="pay_time" data-date-format="yyyy-mm-dd" value="<?php echo $this->scholarship_info["pay_time"];?>">
			</div>
			<input type="hidden" name="scholarship_id" value="<?php echo $this->scholarship_info["scholarship_id"];?>">
			<button type="submit" class="btn btn-primary">提交</button>
		</form>
	</div>
</div>
<?php 
$this->headLink()->appendStylesheet($this->baseUrl("/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css"));
$this->headScript()->appendFile($this->baseUrl("/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"))
                    ->appendFile($this->baseUrl("/plugins/bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN"));
$this->headScript()->appendScript("
                    
    $('.form_datetime').datetimepicker({
        format: 'yyyy-mm-dd hh:ii', 
        language:  'zh-CN',
        todayHighlight: 1,
		startView: 2,
		minView: 2,
        todayBtn:  1,
		autoclose: 1,
    });
                    
", $type = 'text/javascript');
?>