<div id="view-content">
	<h3>学生类型修改</h3>
	<div class="col-md-12">
		<form role="form" class="form form-horizontal" method="post" action="<?php echo $this->baseUrl("/student/type/edit-ok");?>">
			<div class="form-group">
				<label for="college_name">类型名称</label>
				<input type="text" class="form-control" name="stu_type_name" value="<?php echo $this->stu_type["stu_type_name"];?>" required>
				<p class="help-block">如：本科生、硕士研究生、博士研究生</p>
			</div>
			<input type="hidden" value="<?php echo $this->stu_type["stu_type_code"];?>" name ="stu_type_code">
			<button type="submit" class="btn btn-primary">提交</button>
		</form>
	</div>
</div>