<div id="view-content" class="row">
	
	<div class="col-md-12">
	<h3>扣费流水</h3>
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>流水号</th>
                  <th>学号</th>
                  <th>费用编号</th>
                  <th>扣费项目</th>
                  <th>扣费金额</th>
                  <th>银行卡扣费</th>
                  <th>奖学金抵扣</th>
                  <th>扣费时间</th>
                  <th>操作</th>
                </tr>
              </thead>
              <tbody>
              <?php 
              foreach ($this->history_list as $index=>$history) {
                  $amount = "￥" . number_format(floatval($history["amount"]), 2);
                  $key = $history["tuition_key"];
                  $flag = strripos($key, "_");
                  $year = substr($key, $flag + 1, 1);
                  $type = substr($key, $flag + 2, 1);
                  $str = "第" . $year ."年";
                  switch ($type) {
                      case '1': $str .= "学费 &nbsp;&nbsp;"; break;
                      case '2': $str .= "学杂费"; break;
                      case '3': $str .= "住宿费"; break;
                  }
                  echo "
		        <tr>
                  <th scope=\"row\">{$history["history_id"]}</th>
                  <td>{$history["stu_id"]}</td>
                  <td>{$history["tuition_id"]}</td>
                  <td>{$str}</td>
                  <td>{$amount}</td>
                  <td>{$history["cardno"]}</td>
                  <td>{$history["scholarship_id"]}</td>
                  <td>{$history["datetime"]}</td>
                  <td><a href=\"{$this->baseUrl("/tuition/charging/detail/id/" . $history["history_id"])}\" class=\"btn btn-warning btn-xs\"><i class=\"glyphicon glyphicon-edit\"></i>查看详细</a></td>
                </tr>";
              }
                ?>
              </tbody>
            </table>
		</div>
		<div>
		<!-- <a class="btn btn-success" href="<?php echo $this->baseUrl("/tuition/info/add")?>"><i class="glyphicon glyphicon-plus"></i><b>添加</b></a> -->
		</div>
	</div>
</div>

<?php 
$this->headLink()->appendStylesheet($this->baseUrl("/plugins/bootstrap-dialog/dist/css/bootstrap-dialog.min.css"));
$this->headScript()->appendFile($this->baseUrl("/plugins/bootstrap-dialog/dist/js/bootstrap-dialog.min.js"));
$this->headScript()->appendFile($this->baseUrl("/static/js/public.js"));
$this->headScript()->appendScript("
    
    var Public = new PublicClass();
    function delete_confirm(code)
    {
        BootstrapDialog.show({
    		title: '警告',
    	    message: '<h3>删除不可撤销</h3>',
    	    type: BootstrapDialog.TYPE_WARNING,
    	    closable: true,
    	    closeByBackdrop: false,
    	    closeByKeyboard: false,
    	    buttons: [{
                label: '确定',
    	        cssClass: 'btn-warning',
    	        action: function(dialogRef){
                    window.location.href = Public.getBaseUrl('/tuition/info/del/id/' + code);
    	        }
    	    },{
    	        label: '取消',
    	        cssClass: 'btn-default',
    	        action: function(dialogRef){
    	            dialogRef.close();
    	        }
    	    }]
	    });
    }

", $type = 'text/javascript');

?>