<div id="view-content" class="row">
	<div class="col-md-12">
		<h3 class="text-success">已经审核通过列表</h3>
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>序号</th>
                  <th>学院</th>
                  <th>学生学号</th>
                  <th>学生姓名</th>
                  <th>学生年级</th>
                  <th>奖学金名</th>
                  <th>编辑</th>
                </tr>
              </thead>
              <tbody>
              <?php 
              foreach ($this->review_list as $index=>$reviewed) {
                  $index ++;
                  echo 
                    "<tr>
                      <th scope=\"row\">{$index}</th>
                      <td>{$reviewed['dept_name']}</td>
                      <td>{$reviewed['stu_id']}</td>
                      <td>{$reviewed['stu_name']}</td>
                      <td>{$reviewed['stu_grade']}</td>
                      <td>{$reviewed['scholarship_name']}</td>
                      <td><a href=\"{$this->baseUrl("/bursary/check/view/id/" . $reviewed['apply_id'])}\"><i class=\"glyphicon glyphicon-eye-open\"></i>查看<a/></td>
                    </tr>";
              }
                ?>
              </tbody>
            </table>
		</div>
	</div>
	<div class="col-md-12">
			<p><a class="btn btn-info" href="<?php echo $this->baseUrl("/bursary/check/list/");?>">待审核列表</a><a class="btn btn-warning" href="<?php echo $this->baseUrl("/bursary/check/list/type/disagree");?>">审核不通过列表</a></p>
	</div>
</div>

<?php 
$this->headLink()->appendStylesheet($this->baseUrl("/plugins/bootstrap-dialog/dist/css/bootstrap-dialog.min.css"));
$this->headScript()->appendFile($this->baseUrl("/plugins/bootstrap-dialog/dist/js/bootstrap-dialog.min.js"));
$this->headScript()->appendFile($this->baseUrl("/static/js/public.js"));
// $this->headScript()->appendScript("
    
//     var Public = new PublicClass();
//     function delete_confirm(code)
//     {
//         BootstrapDialog.show({
//     		title: '警告',
//     	    message: '<h3>删除不可撤销</h3>',
//     	    type: BootstrapDialog.TYPE_WARNING,
//     	    closable: true,
//     	    closeByBackdrop: false,
//     	    closeByKeyboard: false,
//     	    buttons: [{
//                 label: '确定',
//     	        cssClass: 'btn-warning',
//     	        action: function(dialogRef){
//                     window.location.href = Public.getBaseUrl('/bursary/dept/del/id/' + code);
//     	        }
//     	    },{
//     	        label: '取消',
//     	        cssClass: 'btn-default',
//     	        action: function(dialogRef){
//     	            dialogRef.close();
//     	        }
//     	    }]
// 	    });
//     }

// ", $type = 'text/javascript');

?>
