<div id="view-content" class="row">
	<div class="col-md-12">
		<h3>待审核申请列表</h3>
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>序号</th>
                  <th>学院</th>
                  <th>学生学号</th>
                  <th>学生姓名</th>
                  <th>学生年级</th>
                  <th>奖学金名</th>
                  <th>编辑</th>
                </tr>
              </thead>
              <tbody>
              <?php 
              foreach ($this->apply_list as $index=>$apply) {
                  $index ++;
                  echo 
                    "<tr>
                      <th scope=\"row\">{$index}</th>
                      <td>{$apply['dept_name']}</td>
                      <td>{$apply['stu_id']}</td>
                      <td>{$apply['stu_name']}</td>
                      <td>{$apply['stu_grade']}</td>
                      <td>{$apply['scholarship_name']}</td>
                      <td><a href=\"{$this->baseUrl("/bursary/check/view/id/" . $apply['apply_id'])}\"><i class=\"glyphicon glyphicon-eye-open\"></i>查看<a/></td>
                    </tr>";
              }
                ?>
              </tbody>
            </table>
		</div>
		<div>
		 <a class="btn btn-success" href="<?php echo $this->baseUrl("/bursary/dept/add/id/" . $this->scholarshipinfo["scholarship_id"])?>"><i class="glyphicon glyphicon-plus"></i><b>添加</b></a>
		</div>
	</div>
</div>

<?php 
$this->headLink()->appendStylesheet($this->baseUrl("/plugins/bootstrap-dialog/dist/css/bootstrap-dialog.min.css"));
$this->headScript()->appendFile($this->baseUrl("/plugins/bootstrap-dialog/dist/js/bootstrap-dialog.min.js"));
$this->headScript()->appendFile($this->baseUrl("/static/js/public.js"));
$this->headScript()->appendScript("
    
    var Public = new PublicClass();
    function delete_confirm(code)
    {
        BootstrapDialog.show({
    		title: '警告',
    	    message: '<h3>删除不可撤销</h3>',
    	    type: BootstrapDialog.TYPE_WARNING,
    	    closable: true,
    	    closeByBackdrop: false,
    	    closeByKeyboard: false,
    	    buttons: [{
                label: '确定',
    	        cssClass: 'btn-warning',
    	        action: function(dialogRef){
                    window.location.href = Public.getBaseUrl('/bursary/dept/del/id/' + code);
    	        }
    	    },{
    	        label: '取消',
    	        cssClass: 'btn-default',
    	        action: function(dialogRef){
    	            dialogRef.close();
    	        }
    	    }]
	    });
    }

", $type = 'text/javascript');

?>
