<div id="view-content" class="row">
	<div class="col-md-12">
		<h3>学生条件</h3>
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>学号</th>
                  <th>姓名</th>
                  <th>性别</th>
                  <th>院系</th>
                  <th>类型</th>
                  <th>年级</th>
                  <th>成绩排名</th>
                  <th>翘课次数</th>
                  <th>是否挂科</th>
                  <th>是否有不良记录</th>
                </tr>
              </thead>
              <tbody>
              <?php 
                  $stu_con = $this->stu_con;
                  if ("1" === $stu_con["stu_sex"]) {
                      $stu_sex = "男" ;
                  } else {
                      $stu_sex = "女";
                  }
                  echo 
                    "<tr>
                      <td>{$stu_con["stu_no"]}</td>
                      <td>{$stu_con["stu_name"]}</td>
                      <td>{$stu_sex}</td>
                      <td>{$stu_con["dept_name"]}</td>  
                      <td>{$stu_con["stu_type_name"]}</td>  
                      <td>{$stu_con["stu_grade"]}</td>  
                      <td>{$stu_con["course_grade"]}</td>  
                      <td>{$stu_con["escape_time"]}</td>  
                      <td>{$stu_con["course_no_passed"]}</td>
                      <td>{$stu_con["discipline"]}</td>
                    </tr>";

                ?>
              </tbody>
            </table>
		</div>
		<hr class="col-md-12">
		<h3>审核状态</h3>
		<div class="table-responsive">
			<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>上一步</th>
                  <th>当前</th>
                  <th>下一步</th>
                  
                 </tr>
              </thead>
              <tbody>
              	<tr>
                  <td><?php 
                      echo isset($this->progress["prev"]["flow_name"]) ? $this->progress["prev"]["flow_name"] : "无";
                      ?></td>
                  <td>
                  	<a href="<?php echo $this->baseUrl("/bursary/check/review/id/" . $this->apply_id . "/pass/1/");?>" class="btn btn-success btn-xs"><i class="glyphicon glyphicon-ok"></i>通过</a>
        			<a href="<?php echo $this->baseUrl("/bursary/check/review/id/" . $this->apply_id . "/pass/0/"); ?>" class="btn btn-danger btn-xs"><i class="glyphicon glyphicon-remove"></i>驳回</a>
        		  </td>
                  <td>
                  <?php 
                      echo isset($this->progress["next"]["flow_name"]) ? $this->progress["next"]["flow_name"] : "无";
                      ?>
                  </td>
                </tr>
              </tbody>
        	</table>
		</div>
		<hr class="col-md-12">
		<h3>该生历史奖学金列表</h3>
		<div class="table-responsive">
			<table class="table table-bordered table-condensed">
    			<thead>
                    <tr>
                      <th>序号</th>
                      <th>奖学金年份</th>
                      <th>奖学金名称</th>
                      <th>申请时间</th>
                      <th>是否通过</th>
                      <th>是否发放</th>
                      <th>操作</th>
                    </tr>
                  </thead>
                  <tbody>
           <?php 
              foreach ($this->apply_list as $index=>$apply) {
                  if ($this->apply_id === $apply["apply_id"]) continue;
                  $index ++;
                  $is_pass = ($apply['is_pass']  == 0) ? "<span class=\"text-danger\"><i class=\"glyphicon glyphicon-remove\"></i>未通过</span>" : "<span class=\"text-success\"><i class=\"glyphicon glyphicon-ok\"></i>已通过</span>";
                  $is_paid = ($apply['is_paid']  == 0) ? "<span class=\"text-danger\"><i class=\"glyphicon glyphicon-remove\"></i>未发放</span>" : "<span class=\"text-success\"><i class=\"glyphicon glyphicon-ok\"></i>已发放</span>";
                  echo 
                    "<tr>
                      <th scope=\"row\">{$index}</th>
                      <td>{$apply['scholarship_year']}</td>
                      <td>{$apply['scholarship_name']}</td>
                      <td>{$apply['apply_time']}</td>
                      <td>{$is_pass}</td>
                      <td>{$is_paid}</td>
                      <td><a href=\"{$this->baseUrl("/bursary/check/view/id/" . $apply['apply_id'])}\"><i class=\"glyphicon glyphicon-eye-open\"></i>查看<a/></td>
                    </tr>";
              }
                ?>
                  </tbody>
              </table>
		</div>
	</div>
</div>

<?php 
$this->headLink()->appendStylesheet($this->baseUrl("/plugins/bootstrap-dialog/dist/css/bootstrap-dialog.min.css"));
$this->headScript()->appendFile($this->baseUrl("/plugins/bootstrap-dialog/dist/js/bootstrap-dialog.min.js"));
$this->headScript()->appendFile($this->baseUrl("/static/js/public.js"));
$this->headScript()->appendScript("
    
    var Public = new PublicClass();
    function delete_confirm(code)
    {
        BootstrapDialog.show({
    		title: '警告',
    	    message: '<h3>删除不可撤销</h3>',
    	    type: BootstrapDialog.TYPE_WARNING,
    	    closable: true,
    	    closeByBackdrop: false,
    	    closeByKeyboard: false,
    	    buttons: [{
                label: '确定',
    	        cssClass: 'btn-warning',
    	        action: function(dialogRef){
                    window.location.href = Public.getBaseUrl('/default/user/stu-del/code/' + code);
    	        }
    	    },{
    	        label: '取消',
    	        cssClass: 'btn-default',
    	        action: function(dialogRef){
    	            dialogRef.close();
    	        }
    	    }]
	    });
    }

", $type = 'text/javascript');

?>
