<div id="view-content" class="row">
	<div class="col-md-12">
		<h3>审核状态</h3>
		<div>
			<ol>
		<?php 
		$vote  = true;     //是否需要表决
		$rejected = false; //是否被否决
		foreach ($this->progress as $progress) {
		    if (null === $progress["review_id"]) {
		        //还没有表决
		        echo "<li>" . $progress["flow_name"] . "<i class=\"glyphicon glyphicon-time text-warning\"></i>&nbsp;" ;
		        if (!$rejected && $vote) {
		            echo "<a class=\"btn btn-xs btn-success\" href=\"javascript:agree_confirm('{$this->apply_id}');\">同意</a>";
		            echo "<a class=\"btn btn-xs btn-danger\" href=\"javascript:disagree_confirm('{$this->apply_id}');\">不同意</a>";
		            $vote = false;
		        }
                "</li>";
		    } else {
		        if ('1' === $progress["review_pass"]) {
		            echo "<li>" . $progress["flow_name"] . "<i class=\"glyphicon glyphicon-ok text-success\"></i>[<small>{$progress["comment"]}</small>]</li>";
		        } else if ('0' === $progress["review_pass"]) {
		            $rejected = true;
		            echo "<li>" . $progress["flow_name"] . "<i class=\"glyphicon glyphicon-remove text-danger\"></i>[<small>{$progress["comment"]}</small>]</li>";
		        } else {
		            echo "<li>" . $progress["flow_name"] . "[]</li>";
		        }

		    }

		    
		}
		?>
			
			</ol>
		</div>
		<hr class="col-md-12">
		<h3>学生条件</h3>
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>学号</th>
                  <th>姓名</th>
                  <th>性别</th>
                  <th>院系</th>
                  <th>类型</th>
                  <th>年级</th>
                  <th>成绩排名</th>
                  <th>翘课次数</th>
                  <th>是否挂科</th>
                  <th>是否有不良记录</th>
                </tr>
              </thead>
              <tbody>
              <?php 
                  $stu_con = $this->stu_con;
                  if ("1" === $stu_con["stu_sex"]) {
                      $stu_sex = "男" ;
                  } else {
                      $stu_sex = "女";
                  }
                  echo 
                    "<tr>
                      <td>{$stu_con["stu_no"]}</td>
                      <td>{$stu_con["stu_name"]}</td>
                      <td>{$stu_sex}</td>
                      <td>{$stu_con["dept_name"]}</td>  
                      <td>{$stu_con["stu_type_name"]}</td>  
                      <td>{$stu_con["stu_grade"]}</td>  
                      <td>{$stu_con["course_grade"]}</td>  
                      <td>{$stu_con["escape_time"]}</td>  
                      <td>{$stu_con["course_no_passed"]}</td>
                      <td>{$stu_con["discipline"]}</td>
                    </tr>";

                ?>
              </tbody>
            </table>
		</div>
		<hr class="col-md-12">
		<h3>该生历史奖学金列表</h3>
		<div class="table-responsive">
			<table class="table table-bordered table-condensed">
    			<thead>
                    <tr>
                      <th>序号</th>
                      <th>奖学金年份</th>
                      <th>奖学金名称</th>
                      <th>申请时间</th>
                      <th>是否通过</th>
                      <th>是否发放</th>
                      <th>操作</th>
                    </tr>
                  </thead>
                  <tbody>
           <?php 
//            var_dump($this->apply_list);
              foreach ($this->apply_list as $index=>$apply) {
                  if ($this->apply_id === $apply["apply_id"]) {
                      $class="bg-success";
                  } else {
                      $class = "";
                  }
                  $index ++;
                  if ($apply['is_pass']  === '0') {
                      $is_pass = "<span class=\"text-danger\"><i class=\"glyphicon glyphicon-remove\"></i>未通过</span>";
                  } else if ($apply['is_pass']  === '1') {
                      $is_pass = "<span class=\"text-success\"><i class=\"glyphicon glyphicon-ok\"></i>已通过</span>";
                  } else {
                      $is_pass = "<span class=\"text-info\"><i class=\"glyphicon glyphicon-refresh\"></i>待审核</span>";
                  }
                  
                  //发放状态
                  if (null === $apply['is_paid']) {
                      $is_paid = "";
                  } else if ($apply['is_paid']  === '0') {
                      $is_paid = "<span class=\"text-info\"><i class=\"glyphicon glyphicon-hourglass\"></i>待发放</span>";
                  } else if ($apply['is_paid']  === '1') {
                      $is_paid = "<span class=\"text-success\"><i class=\"glyphicon glyphicon-ok\"></i>已发放</span>";
                  } else if ($apply['is_paid']  === '2'){
                      $is_paid = "<span class=\"text-danger\"><i class=\"glyphicon glyphicon-remove\"></i>不发放</span>";
                  }
//                   $is_pass = ($apply['is_pass']  === '2') ? "<span class=\"text-danger\"><i class=\"glyphicon glyphicon-remove\"></i>未通过</span>" : "<span class=\"text-success\"><i class=\"glyphicon glyphicon-ok\"></i>已通过</span>";
//                   $is_paid = ($apply['is_paid']  === '0') ? "<span class=\"text-danger\"><i class=\"glyphicon glyphicon-remove\"></i>未发放</span>" : "<span class=\"text-success\"><i class=\"glyphicon glyphicon-ok\"></i>已发放</span>";
                  echo 
                    "<tr class=\"{$class}\">
                      <th scope=\"row\">{$index}</th>
                      <td>{$apply['scholarship_year']}</td>
                      <td>{$apply['scholarship_name']}</td>
                      <td>{$apply['apply_time']}</td>
                      <td>{$is_pass}</td>
                      <td>{$is_paid}</td>
                      <td><a href=\"{$this->baseUrl("/bursary/check/view/id/" . $apply['apply_id'])}\"><i class=\"glyphicon glyphicon-eye-open\"></i>查看<a/></td>
                    </tr>";
              }
                ?>
                  </tbody>
              </table>
		</div>
	</div>
</div>

<?php 
$this->headLink()->appendStylesheet($this->baseUrl("/plugins/bootstrap-dialog/dist/css/bootstrap-dialog.min.css"));
$this->headScript()->appendFile($this->baseUrl("/plugins/bootstrap-dialog/dist/js/bootstrap-dialog.min.js"));
$this->headScript()->appendFile($this->baseUrl("/static/js/public.js"));
$this->headScript()->appendScript("
    
    var Public = new PublicClass();
    function agree_confirm(id)
    {
        BootstrapDialog.show({
    		title: '同意',
    	    message: $('<textarea name=\"comment\" class=\"form-control\" placeholder=\"同意\">同意</textarea>'),
    	    type: BootstrapDialog.TYPE_SUCCESS,
    	    closable: true,
    	    closeByBackdrop: false,
    	    closeByKeyboard: false,
    	    buttons: [{
                label: '确定',
    	        cssClass: 'btn-success',
    	        action: function(dialogRef){
                     var comment = dialogRef.getModalBody().find('textarea').val();
                     if ('' == comment) {
                        alert(' 请填写意见');
                        return false;
                     }
                     window.location.href = '" . $this->baseUrl('/bursary/check/review/pass/1/id/') . "'+id+'/comment/'+encodeURI(comment)
    	        }
    	    },{
    	        label: '取消',
    	        cssClass: 'btn-default',
    	        action: function(dialogRef){
    	            dialogRef.close();
    	        }
    	    }]
	    });
    }
    
   function disagree_confirm(id)
    {
        BootstrapDialog.show({
    		title: '同意',
    	    message: $('<textarea name=\"comment\" class=\"form-control\" placeholder=\"不同意\">不同意</textarea>'),
    	    type: BootstrapDialog.TYPE_DANGER,
    	    closable: true,
    	    closeByBackdrop: false,
    	    closeByKeyboard: false,
    	    buttons: [{
                label: '确定',
    	        cssClass: 'btn-danger',
    	        action: function(dialogRef){
                    var comment = dialogRef.getModalBody().find('textarea').val();
                    if ('' == comment) {
                        alert(' 请填写意见');
                        return false;
                    }
                    window.location.href = '" . $this->baseUrl('/bursary/check/review/pass/1/id/') ."'+id+'/comment/'+encodeURI(comment)
    	        }
    	    },{
    	        label: '取消',
    	        cssClass: 'btn-default',
    	        action: function(dialogRef){
    	            dialogRef.close();
    	        }
    	    }]
	    });
    }

", $type = 'text/javascript');

?>
