<div id="view-content">
	<div class="col-md-12">
	<h3>用户列表</h3>
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>序号</th>
                  <th>学工号</th>
                  <th>系统角色</th>
                  <th>邮箱</th>
                  <th>手机</th>
                  <th>修改系统角色</th>
                </tr>
              </thead>
              <tbody>
              <?php 
              foreach ($this->user_list as $index=>$user) {
                  $index ++;

                  echo 
                    "<tr>
                      <th scope=\"row\">{$index}</th>
                      <td>{$user["user_id"]}</td>
                      <td>{$user["type_name"]}</td>  
                      <td>{$user["email"]}</td>  
                      <td>{$user["phone"]}</td>  
                      <td><a href=\"{$this->baseUrl("/user/account/set-auth/id/" . $user["user_id"])}\" class=\"btn btn-warning btn-xs\"><i class=\"glyphicon glyphicon-edit\"></i> 修改</a></td>  
                    </tr>";
              }
                ?>
              </tbody>
            </table>
		</div>
		<div>
		 <a class="btn btn-success" href="<?php echo $this->baseUrl("/user/manager/add")?>"><i class="glyphicon glyphicon-plus"></i><b>添加管理员</b></a>
		</div>
	</div>
</div>

<?php 
$this->headLink()->appendStylesheet($this->baseUrl("/plugins/bootstrap-dialog/dist/css/bootstrap-dialog.min.css"));
$this->headScript()->appendFile($this->baseUrl("/plugins/bootstrap-dialog/dist/js/bootstrap-dialog.min.js"));
$this->headScript()->appendFile($this->baseUrl("/static/js/public.js"));
$this->headScript()->appendScript("
    
    var Public = new PublicClass();
    function delete_confirm(code)
    {
        BootstrapDialog.show({
    		title: '警告',
    	    message: '<h3>删除不可撤销</h3>',
    	    type: BootstrapDialog.TYPE_WARNING,
    	    closable: true,
    	    closeByBackdrop: false,
    	    closeByKeyboard: false,
    	    buttons: [{
                label: '确定',
    	        cssClass: 'btn-warning',
    	        action: function(dialogRef){
                    window.location.href = Public.getBaseUrl('/student/info/del/code/' + code);
    	        }
    	    },{
    	        label: '取消',
    	        cssClass: 'btn-default',
    	        action: function(dialogRef){
    	            dialogRef.close();
    	        }
    	    }]
	    });
    }

", $type = 'text/javascript');

?>
