<div id="view-content">
	<div class="row">
		<h3>密码重置——<small>用户名搜索</small></h3>
		<div class="col-md-12">
			<form role="form" class="form form-horizontal" method="post" action="<?php echo $this->baseUrl("/user/account/reset");?>">
			 <div class="form-group">
                <label for="InputPassword0">用户名/学号/工号</label>
                <input type="text" class="form-control" name="user_id" id="user_id" required placeholder="用户名/学号/工号">
              </div>
               <div class="form-group">
                  <button type="submit" class="btn btn-primary">搜索</button>
              </div>
			</form>
		</div>
	</div>
</div>