
<div id="view-content">
<h3>设定用户<b><?php echo $this->user_id;?></b>角色</h3>
	<div class="col-md-12">
	<form role="form" class="form form-horizontal" method="post" action="<?php echo $this->baseUrl("/user/account/set-auth-ok");?>">
	<div class="form-group">
				<label for="college_name">角色代码</label>
	<?php 
    $user_type_list = $this->user_type_list;
    $len = count($user_type_list);
    for($i = 0; $i < $len; $i ++) {
    	echo "<label class=\"checkbox-inline\">
    			 <input type=\"radio\" name=\"type_code\" value=\"{$user_type_list[$i]['type_code']}\" required>{$user_type_list[$i]["type_name"]}
    		</label>";
    }
  ?>
  </div>
  <input type="hidden" name="user_id" value="<?php echo $this->user_id;?>">
  <button type="submit" class="btn btn-primary">提交</button>
  </form>
  </div>
</div>