<div id="view-content">
	<h3>学费修改</h3>
	<div class="col-md-12">
		<form role="form" class="form form-horizontal" method="post" action="<?php echo $this->baseUrl("/tuition/info/edit-ok");?>">
			<div class="form-group">
				<label for="college_name">入学年级</label>
				<input type="text" class="form-control" name="grade" maxlength="4" required value="<?php echo $this->tuition["grade"];?>">
			</div>
			<div class="form-group">
				<label for="college_name">核定年份</label>
				<input type="text" class="form-control" name="year" maxlength="4" required value="<?php echo $this->tuition["year"];?>">
			</div>
			<div class="form-group">
				<label for="dept_code">所属学院</label>
    			<select class="form-control" name="dept_code">
    			<?php 
    			$dept_list = $this->dept_list;
    			$parent_code = null;
    			$len = count($dept_list);
    			for ($i = 0; $i < $len; $i ++) {
    			    $selected = ($this->tuition["dept_code"] == $dept_list[$i]["dept_code"]) ? "selected" : "";
    			    if ($dept_list[$i]["parent_code"] !== $parent_code) {
    			        $parent_code = $dept_list[$i]["parent_code"];
    			        echo "<optgroup label=\"{$dept_list[$i]["dept_name"]}\"><option value=\"{$dept_list[$i]["dept_code"]}\" {$selected}>{$dept_list[$i]["dept_name"]}</option>";
    			    } else {
    			        echo "<option value=\"{$dept_list[$i]["dept_code"]}\"  \"{$selected}\">{$dept_list[$i]["dept_name"]}</option>";
    			        if ($i + 1 == $len) {
    			            echo "</optgroup>";
    			        } else if ($parent_code != $dept_list[$i + 1]["parent_code"]) {
    			            echo "</optgroup>";
    			        }
    			    }
    			}
    			?>
                 
                </select>
			</div>
			<div class="form-group">
				<label for="dept_code">学生类型</label>
    			<select class="form-control" name="stu_type">
    				<?php 
    				    $stu_type_list = $this->stu_type_list;
    				    $len = count($stu_type_list);
    				    for($i = 0; $i < $len; $i ++) {
    				        $selected = ($this->tuition["stu_type"] == $stu_type_list[$i]["stu_type_code"]) ? "selected" : "";
//     				        echo $selected;exit();
    				        echo "<option value=\"{$stu_type_list[$i]["stu_type_code"]}\" {$selected}>{$stu_type_list[$i]["stu_type_name"]}</option>";
    				    }
    				?>
    			</select>
    		</div>
    		<div class="form-group">
    			<label for="dept_code">学费金额</label>
    			<input type="text" name="tuition_1" class="form-control" value="<?php echo $this->tuition["tuition_1"];?>">
    		</div>
    		<div class="form-group">
    			<label for="dept_code">学杂费金额</label>
    			<input type="text" name="tuition_2" class="form-control" value="<?php echo $this->tuition["tuition_2"];?>">
    		</div>
    		<div class="form-group">
    			<label for="dept_code">住宿费金额</label>
    			<input type="text" name="tuition_3" class="form-control" value="<?php echo $this->tuition["tuition_3"];?>">
    		</div>
    		<input type="hidden" name="tuition_id" value="<?php echo $this->tuition["tuition_id"];?>">
			<button type="submit" class="btn btn-primary">提交</button>
		</form>
	</div>
</div>