<div id="view-content" class="row">
	<div class="col-md-12">
	<h3>费用列表</h3>
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>序号</th>
                  <th>年级</th>
                  <th>学年</th>
                  <th>院系（专业）</th>
                  <th>学生类型</th>
                  <th>学费</th>
                  <th>学杂费</th>
                  <th>住宿费</th>
                  <th>编辑</th>
                </tr>
              </thead>
              <tbody>
              <?php 
              foreach ($this->tuition_list as $index=>$tuition) {
                  $index ++;
                  $tuition_1 = number_format(floatval($tuition["tuition_1"]), 2);
                  $tuition_2 = number_format(floatval($tuition["tuition_2"]), 2);
                  $tuition_3 = number_format(floatval($tuition["tuition_3"]), 2);
                  echo "
		        <tr>
                  <th scope=\"row\">{$index}</th>
                  <td>{$tuition["grade"]}</td>
                  <td>{$tuition["year"]}</td>
                  <td>{$tuition["dept_name"]}</td>
                  <td>{$tuition["stu_type_name"]}</td>
                  <td>{$tuition_1}</td>
                  <td>{$tuition_2}</td>
                  <td>{$tuition_3}</td>
                  <td><a href=\"{$this->baseUrl("/tuition/info/edit/id/" . $tuition["tuition_id"])}\" class=\"btn btn-warning btn-xs\"><i class=\"glyphicon glyphicon-edit\"></i>修改</a><a href=\"javascript:delete_confirm('{$tuition["tuition_id"]}');\" class=\"btn btn-danger btn-xs\"><i class=\"glyphicon glyphicon-trash\"></i>删除</a></td>
                </tr>";
              }
                ?>
              </tbody>
            </table>
		</div>
		<div>
		 <a class="btn btn-success" href="<?php echo $this->baseUrl("/tuition/info/add")?>"><i class="glyphicon glyphicon-plus"></i><b>添加</b></a>
		</div>
	</div>
</div>

<?php 
$this->headLink()->appendStylesheet($this->baseUrl("/plugins/bootstrap-dialog/dist/css/bootstrap-dialog.min.css"));
$this->headScript()->appendFile($this->baseUrl("/plugins/bootstrap-dialog/dist/js/bootstrap-dialog.min.js"));
$this->headScript()->appendFile($this->baseUrl("/static/js/public.js"));
$this->headScript()->appendScript("

    function delete_confirm(code)
    {
        BootstrapDialog.show({
    		title: '警告',
    	    message: '<h3>删除不可撤销</h3>',
    	    type: BootstrapDialog.TYPE_WARNING,
    	    closable: true,
    	    closeByBackdrop: false,
    	    closeByKeyboard: false,
    	    buttons: [{
                label: '确定',
    	        cssClass: 'btn-warning',
    	        action: function(dialogRef){
                    window.location.href = \"". $this->baseUrl('/tuition/info/del/id/') . "\"+ code;
    	        }
    	    },{
    	        label: '取消',
    	        cssClass: 'btn-default',
    	        action: function(dialogRef){
    	            dialogRef.close();
    	        }
    	    }]
	    });
    }

", $type = 'text/javascript');

?>