<div id="view-content" class="row">
	
	<div class="col-md-12">
		<h3>欠费列表</h3>
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>序号</th>
                  <th>学号</th>
                  <th>姓名</th>
                  <th>学院</th>
                  <th>年级</th>
                  <th>欠费项目</th>
                  <th>操作</th>
                </tr>
              </thead>
              <tbody>
              <?php 
              foreach ($this->deduct_list as $index=>$deduct) {
                  $str = "<ul>";
                  foreach ($deduct as $key=>$value) {
                      $is_exist = strripos($key, "tuition", 0);
                      if (false !== $is_exist) {
                          if (floatval($value > 0.0)) {
                              $flag = strripos($key, "_");
                              $year = substr($key, $flag + 1, 1);
                              $type = substr($key, $flag + 2, 1);
                              $str .= "<li>第" . $year ."年";
                              switch ($type) {
                                  case '1': $str .= "学费 &nbsp;&nbsp;"; break;
                                  case '2': $str .= "学杂费"; break;
                                  case '3': $str .= "住宿费"; break;
                              }
                              $str .= " ￥ " . floatval($value) . "元";
                          }
                      }

                  }
                  $str .= "</ul>";
                  $i = $index + 1;
                  echo "
		        <tr>
                  <th scope=\"row\">{$i}</th>
                  <td>{$deduct["stu_id"]}</td>
                  <td>{$deduct["stu_name"]}</td>
                  <td>{$deduct["dept_name"]}</td>
                  <td>{$deduct["stu_grade"]}</td>
                  <td>{$str}</td>
                  <td><a href=\"{$this->baseUrl("/tuition/charging/list/id/" . $deduct["stu_id"])}\" class=\"btn btn-warning btn-xs\"><i class=\"glyphicon glyphicon-edit\"></i>查看流水</a></td>
                </tr>";
              }
                ?>
              </tbody>
            </table>
		</div>
	</div>
	<div class="col-md-12">
		<a class="btn btn-success" href="<?php echo $this->baseUrl("/tuition/fee/reflesh")?>"><i class="glyphicon glyphicon-refresh"></i><b>刷新数据库</b></a> 
	</div>
</div>

<?php 
$this->headLink()->appendStylesheet($this->baseUrl("/plugins/bootstrap-dialog/dist/css/bootstrap-dialog.min.css"));
$this->headScript()->appendFile($this->baseUrl("/plugins/bootstrap-dialog/dist/js/bootstrap-dialog.min.js"));
$this->headScript()->appendFile($this->baseUrl("/static/js/public.js"));


?>