<div id="view-content">
	<div class="row">
		<div class="col-md-12">
			<h3>我的条件</h3>
			<p class="col-md-3">成绩排名：<b><?php echo $this->condition["course_grade"];?></b></p>
			<p class="col-md-3">不及格科目数：<b><?php echo $this->condition["course_no_passed"];?></b></p>
			<p class="col-md-3">逃课次数：<b><?php echo $this->condition["escape_time"];?></b></p>
			<p class="col-md-3">违纪情况：<b><?php echo $this->condition["discipline"];?></b></p>
		</div>
		<hr class="col-md-12">
		<?php 
		if (isset($this->scholarship_apply_record["apply_id"])) {
		?>
		 <div class="col-md-12">
		 	<a href="<?php echo $this->baseUrl("/default/bursary/view/id/" . $this->scholarship_apply_record["apply_id"])?>" class="btn btn-success">已申请</a>
		 </div>
		<?php 
		}  else { 
		?>
		 <div class="col-md-12">
			<h3><?php echo $this->bursary["scholarship_name"];?></h3>
			<form class="form" method="post" action="<?php echo $this->baseUrl("/default/bursary/apply-ok");?>">
				<input type="hidden" name="id" value="<?php echo $this->bursary["scholarship_id"];?>">
				<button type="submit" class="btn btn-primary">确定申请</button>
			</form> 
		</div>
	<?php 
		}
		?>

	</div>
</div>