<div id="view-content">
	<h3><b><?php echo $this->scholarshipinfo["scholarship_name"];?></b>申请条件</h3>
	<div class="col-md-12">
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>序号</th>
                  <th>条件表达式</th>
                  <th>是否满足</th>
                </tr>
              </thead>
              <tbody>
              <?php 
              foreach ($this->condition_list as $index=>$condition) {
                  switch ($condition['key']) {
                      case "course_grade": $condition['key'] = "成绩排名"; break;
                      case "escape_time": $condition['key'] = "逃课次数"; break;
                      case "course_no_passed": $condition['key'] = "挂科门数"; break;
                      case "discipline": $condition['key'] = "不良记录"; break;
                  }
                  $expression = $condition['key'] . $condition['symbol'] .$condition['value'];
                  $index ++;
                  echo 
                    "<tr>
                      <td>{$index}</td>
                      <td>{$expression}</td>
                      <td></td>
                    </tr>";
              }
                ?>
              </tbody>
            </table>
		</div>
	</div>
</div>
