<div id="view-content">
	<h3><b><?php echo $this->scholarshipinfo["scholarship_name"];?></b>名额分布</h3>
	<div class="col-md-12">
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>序号</th>
                  <th>学院</th>
                  <th>年级</th>
                  <th>名额</th>
                </tr>
              </thead>
              <tbody>
              <?php 
              foreach ($this->scholarship_distribute as $index=>$distribute) {
                  $index ++;
                  echo 
                    "<tr>
                      <th scope=\"row\">{$index}</th>
                      <td>{$distribute['dept_name']}</td>
                      <td>{$distribute['scholarship_year']}</td>
                      <td>{$distribute['scholarship_dept_num']}</td>
                    </tr>";
              }
                ?>
              </tbody>
            </table>
		</div>
	</div>
</div>

<?php 
$this->headLink()->appendStylesheet($this->baseUrl("/plugins/bootstrap-dialog/dist/css/bootstrap-dialog.min.css"));
$this->headScript()->appendFile($this->baseUrl("/plugins/bootstrap-dialog/dist/js/bootstrap-dialog.min.js"));
$this->headScript()->appendFile($this->baseUrl("/static/js/public.js"));


?>
