<div id="view-content" class="row">
	<div class="col-md-12">
	<h3><b><?php echo $this->scholarshipinfo["scholarship_name"];?></b>申请发放流程</h3>
	<br><br>
	<p class="lead">
	<?php 
	   $flow = $this->flow_list;
	   $len = count($flow);
	   for ($i = 0; $i < $len; $i ++)
	   {
	       echo $flow[$i]['flow_name'] . "<small>[" . $flow[$i]['check_role_id'] . "]</small>";
	       if ($i < $len - 1) 
	           echo "-->";
	   }

 ?>
	</p>
	
	</div>
</div>