<div id="view-content" class="row">
	<div class="col-md-12">
		<h3>审核进度</h3>
		<br><br>
		<p class="lead">
		<?php 
		$progress = $this->progress;
		$len = count($progress);
		for ($i = 0; $i < $len; $i ++) {
		    if (null === $progress[$i]["review_id"]) {
		        //还没有表决
		        echo "<span title=\"待审核\">" . $progress[$i]["flow_name"] . "<i class=\"glyphicon glyphicon-time text-warning\"></i>&nbsp;</span>";
		    } else {
		        if ('1' === $progress[$i]["review_pass"]) {
		            echo "<span  title=\"已通过\">" . $progress[$i]["flow_name"] . "<i class=\"glyphicon glyphicon-ok text-success\"></i>[<small>{$progress[$i]["comment"]}</small>]</span>";
		        } else if ('0' === $progress[$i]["review_pass"]) {
		            echo "<span  title=\"不通过\">" . $progress[$i]["flow_name"] . "<i class=\"glyphicon glyphicon-remove text-danger\"></i>[<small>{$progress[$i]["comment"]}</small>]</span>";
		            break;
		        } else {
		            echo "<span  title=\"待审核\">" . $progress[$i]["flow_name"] . "</span>";
		        }

		    }
		    if ($i < $len - 1)
		        echo "-->";
		    
		}
		?>
		</p>
</div>
</div>