<div id="view-content">
	<h3>教工添加</h3>
	<div class="col-md-12">
		<form role="form" class="form form-horizontal" method="post" action="<?php echo $this->baseUrl("/faculty/info/add-ok");?>">
			<div class="form-group">
				<label for="college_name">工号</label>
				<input type="text" class="form-control" name="faculty_id" required>
			</div>
			<div class="form-group">
				<label for="college_name">姓名</label>
				<input type="text" class="form-control" name="faculty_name" required>
			</div>
			<div class="form-group">
				<label for="dept_code">性别</label>
    			<select class="form-control" name="faculty_sex">
    				<option value="1" selected>男</option>
    				<option value="0">女</option>
    			</select>
    		</div>

			<div class="form-group">
				<label for="dept_code">所属学院</label>
    			<select class="form-control" name="dept_code">
    			<option>请选择</option>
    			<?php 
    			$dept_list = $this->dept_list;
    			$parent_code = null;
    			$len = count($dept_list);
    			for ($i = 0; $i < $len; $i ++) {
    			    if ($dept_list[$i]["parent_code"] !== $parent_code) {
    			        $parent_code = $dept_list[$i]["parent_code"];
    			        echo "<optgroup label=\"{$dept_list[$i]["dept_name"]}\"><option value=\"{$dept_list[$i]["dept_code"]}\">{$dept_list[$i]["dept_name"]}</option>";
    			    } else {
    			        echo "<option value=\"{$dept_list[$i]["dept_code"]}\">{$dept_list[$i]["dept_name"]}</option>";
    			        if ($i + 1 == $len) {
    			            echo "</optgroup>";
    			        } else if ($parent_code != $dept_list[$i + 1]["parent_code"]) {
    			            echo "</optgroup>";
    			        }
    			    }
    			}
    			?>
                 
                </select>
			</div>
			<div class="form-group">
				<label for="email">邮箱</label>
				<input type="email" class="form-control" name="email" required>
			</div>
			<div class="form-group">
				<label for="phone">手机</label>
				<input type="text" class="form-control" name="phone" required>
			</div>
			<button type="submit" class="btn btn-primary">提交</button>
		</form>
	</div>
</div>