<div id="view-content">
	<div class="col-md-12">
	<h3>教职工列表</h3>
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>序号</th>
                  <th>工号</th>
                  <th>姓名</th>
                  <th>性别</th>
                  <th>院系</th>
                </tr>
              </thead>
              <tbody>
              <?php 
              foreach ($this->faculty_list as $index=>$faculty) {
                  $index ++;
                  if ("1" === $faculty["faculty_sex"]) {
                      $faculty_sex = "男" ;
                  } else {
                      $faculty_sex = "女";
                  }
                  echo 
                    "<tr>
                      <th scope=\"row\">{$index}</th>
                      <td>{$faculty["faculty_id"]}</td>
                      <td>{$faculty["faculty_name"]}</td>
                      <td>{$faculty_sex}</td>
                      <td>{$faculty["dept_name"]}</td>  
                    </tr>";
              }
                ?>
              </tbody>
            </table>
		</div>
		<div>
		 <a class="btn btn-success" href="<?php echo $this->baseUrl("/faculty/info/add")?>"><i class="glyphicon glyphicon-plus"></i><b>添加</b></a>
		</div>
	</div>
</div>

<?php 
$this->headLink()->appendStylesheet($this->baseUrl("/plugins/bootstrap-dialog/dist/css/bootstrap-dialog.min.css"));
$this->headScript()->appendFile($this->baseUrl("/plugins/bootstrap-dialog/dist/js/bootstrap-dialog.min.js"));
$this->headScript()->appendFile($this->baseUrl("/static/js/public.js"));
$this->headScript()->appendScript("
    
    var Public = new PublicClass();
    function delete_confirm(code)
    {
        BootstrapDialog.show({
    		title: '警告',
    	    message: '<h3>删除不可撤销</h3>',
    	    type: BootstrapDialog.TYPE_WARNING,
    	    closable: true,
    	    closeByBackdrop: false,
    	    closeByKeyboard: false,
    	    buttons: [{
                label: '确定',
    	        cssClass: 'btn-warning',
    	        action: function(dialogRef){
                    window.location.href = Public.getBaseUrl('/faculty/info/del/code/' + code);
    	        }
    	    },{
    	        label: '取消',
    	        cssClass: 'btn-default',
    	        action: function(dialogRef){
    	            dialogRef.close();
    	        }
    	    }]
	    });
    }

", $type = 'text/javascript');

?>
