
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>奖学金平台-登陆</title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo $this->baseUrl("/plugins/bootstrap/css/bootstrap.min.css")?>" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?php echo $this->baseUrl("/static/css/signin.css")?>" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <form class="form-signin" action="<?php echo $this->baseUrl("/default/account/valid/")?>" method="post">
        <h2 class="form-signin-heading">请登陆</h2>
        <label for="inputUsr" class="sr-only">学工号</label>
        <input type="text" id="user_id" name="user_id" class="form-control" placeholder="学工号" required autofocus>
        <label for="inputPassword" class="sr-only">密码</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="密码" required>
        <div class="checkbox">
        	<p class="help-block"><a href="<?php echo $this->baseUrl("/default/account/forget")?>" target="_blank">忘记密码</a></p>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登陆</button>
      </form>

    </div> <!-- /container -->

  </body>
</html>
