<div id="view-content">
	<div class="row">
		<h3>修改密码</h3>
		<div class="col-md-12">
			<form role="form" class="form form-horizontal" method="post" action="<?php echo $this->baseUrl("/default/account/reset-ok");?>">
			 <div class="form-group">
                <label for="InputPassword0">当前密码</label>
                <input type="password" class="form-control" name="c_pwd" id="InputPassword0" placeholder="原密码">
              </div>
               <div class="form-group">
                <label for="InputPassword1">新密码</label>
                <input type="password" class="form-control" name="n_pwd" id="InputPassword1" required placeholder="新密码">
              </div>
               <div class="form-group">
                <label for="InputPassword2">确认新密码</label>
                <input type="password" class="form-control" name="n_pwd_" id="InputPassword2" required placeholder="确认新密码">
              </div>
               <div class="form-group">
                  <button type="submit" class="btn btn-primary">提交</button>
              </div>
			</form>
		</div>
	</div>
</div>