<div id="view-content">
	<div class="col-md-12">
		<h3>学生银行卡</h3>
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>序号</th>
                  <th>学号</th>
                  <th>姓名</th>
                  <th>院系</th>
                  <th>卡号</th>
			      <th>添加时间</th>
			      <th>审核人</th>
			      <th>操作</th>
                </tr>
              </thead>
              <tbody>
              <?php 
              foreach ($this->bank_list as $index=>$bank) {
                  $index ++;
                  echo 
                    "<tr>
                      <th scope=\"row\">{$index}</th>
                      <td>{$bank["stu_no"]}</td>
                      <td>{$bank["stu_name"]}</td>
                      <td>{$bank["dept_name"]}</td>  
                      <td>{$bank["cardno"]}</td>  
                      <td>{$bank["add_time"]}</td>  
                      <td>{$bank["operator"]}</td>  
                      <td><a href=\"{$this->baseUrl("/tuition/bank/edit/id/" . $bank["stu_no"])}\" class=\"btn btn-warning btn-xs\"><i class=\"glyphicon glyphicon-edit\"></i>修改</a><a href=\"javascript:delete_confirm('{$bank["card_id"]}');\" class=\"btn btn-danger btn-xs\"><i class=\"glyphicon glyphicon-trash\"></i>删除</a></td>
                    </tr>";
              }
                ?>
              </tbody>
            </table>
		</div>
	</div>
</div>

<?php 
$this->headLink()->appendStylesheet($this->baseUrl("/plugins/bootstrap-dialog/dist/css/bootstrap-dialog.min.css"));
$this->headScript()->appendFile($this->baseUrl("/plugins/bootstrap-dialog/dist/js/bootstrap-dialog.min.js"));
$this->headScript()->appendFile($this->baseUrl("/static/js/public.js"));
$this->headScript()->appendScript("
    
    function delete_confirm(id)
    {
        BootstrapDialog.show({
    		title: '警告',
    	    message: '<h3>删除不可撤销</h3>',
    	    type: BootstrapDialog.TYPE_WARNING,
    	    closable: true,
    	    closeByBackdrop: false,
    	    closeByKeyboard: false,
    	    buttons: [{
                label: '确定',
    	        cssClass: 'btn-warning',
    	        action: function(dialogRef){
                    window.location.href = '" . $this->baseUrl('/tuition/bank/del/id/')  ."' + id;
    	        }
    	    },{
    	        label: '取消',
    	        cssClass: 'btn-default',
    	        action: function(dialogRef){
    	            dialogRef.close();
    	        }
    	    }]
	    });
    }

", $type = 'text/javascript');

?>
