<div id="view-content">
	<h3>系统角色添加</h3>
	<div class="col-md-12">
		<form role="form" class="form form-horizontal" method="post" action="<?php echo $this->baseUrl("/user/auth/add-ok");?>">
			<div class="form-group">
				<label for="college_name">角色代码</label>
				<input type="text" class="form-control" name="type_code" maxlength="2" required>
			</div>
			<div class="form-group">
				<label for="college_name">角色名字</label>
				<input type="text" class="form-control" name="type_name" required>
			</div>
			<div class="form-group">
				<label for="dept_code">父级角色</label>
<!-- 				<label class="checkbox-inline"> -->
<!--     			    <input type="checkbox" id="parent_code_0" name="parent_code[]" value="0">游客 -->
<!--     			    </label> -->
				 <?php 
    			$type_list = $this->type_list;
    			$parent_code = null;
    			$len = count($type_list);
    			for ($i = 0; $i < $len; $i ++) {
    			    $j = $i + 1;
    			    //     			    echo "<option value=\"{$flow_list[$i]['flow_id']}\">" . $flow_list[$i]["flow_name"] . "</option>";
    			    echo "<label class=\"checkbox-inline\">
    			    <input type=\"checkbox\" id=\"parent_code_{$j}\" name=\"parent_code[]\" value=\"{$type_list[$i]['type_code']}\">{$type_list[$i]["type_name"]}[{$type_list[$i]['type_code']}]
    			    </label>";
    			}

    			?>
			</div>
			<button type="submit" class="btn btn-primary">提交</button>
		</form>
	</div>
</div>