<div id="view-content">
	<h3>角色列表</h3>
	<div class="col-md-12">
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
<!--                   <th>序号</th> -->
                  <th>角色代码</th>
                  <th>角色名称</th>
                  <th>父级角色</th>
                  <th>编辑</th>
                </tr>
              </thead>
              <tbody>
              <?php 
              foreach ($this->type_list as $index=>$type) {
                  $index ++;
                  $parent_name = "";
                  foreach ($type["parent"] as $parent) {
                      $parent_name .= "<span class=\"label label-default\">" . $parent["parent_name"] . "</span>";
                  }
                  echo 
                    "<tr>
                      <!--<th scope=\"row\">{$index}</th> -->
                      <td>{$type["type_code"]}</td>
                      <td><span class=\"label label-primary\">{$type["type_name"]}</span></td>
                      <td>{$parent_name}</td>
                      <td><a href=\"{$this->baseUrl("/user/auth/edit/code/" . $type['type_code'])}\" class=\"btn btn-warning btn-xs\"><i class=\"glyphicon glyphicon-edit\"></i>修改</a><a href=\"javascript:delete_confirm('{$type['type_code']}');\" class=\"btn btn-danger btn-xs\"><i class=\"glyphicon glyphicon-trash\"></i>删除</a></td>
                    </tr>";
              }
                ?>
              </tbody>
            </table>
		</div>
		<div>
		 <a class="btn btn-success" href="<?php echo $this->baseUrl("/user/auth/add")?>"><i class="glyphicon glyphicon-plus"></i><b>添加</b></a>
		</div>
	</div>
</div>

<?php 
$this->headLink()->appendStylesheet($this->baseUrl("/plugins/bootstrap-dialog/dist/css/bootstrap-dialog.min.css"));
$this->headScript()->appendFile($this->baseUrl("/plugins/bootstrap-dialog/dist/js/bootstrap-dialog.min.js"));
$this->headScript()->appendFile($this->baseUrl("/static/js/public.js"));
$this->headScript()->appendScript("
    
    var Public = new PublicClass();
    function delete_confirm(code)
    {
        BootstrapDialog.show({
    		title: '警告',
    	    message: '<h3>删除不可撤销</h3>',
    	    type: BootstrapDialog.TYPE_WARNING,
    	    closable: true,
    	    closeByBackdrop: false,
    	    closeByKeyboard: false,
    	    buttons: [{
                label: '确定',
    	        cssClass: 'btn-warning',
    	        action: function(dialogRef){
                    window.location.href = Public.getBaseUrl('/user/auth/del/code/' + code);
    	        }
    	    },{
    	        label: '取消',
    	        cssClass: 'btn-default',
    	        action: function(dialogRef){
    	            dialogRef.close();
    	        }
    	    }]
	    });
    }

", $type = 'text/javascript');

?>
