<div id="view-content">
	<h3>单位列表</h3>
	<div class="col-md-12">
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>序号</th>
                  <th>单位全称</th>
                  <th>单位名称</th>
                  <th>上级单位</th>
                </tr>
              </thead>
              <tbody>
              <?php 
              foreach ($this->dept_list as $index=>$dept) {
                  $index ++;
                  $dept_full_name = $dept["dept_full_name"];
                  $dept_name = $dept["dept_name"];
                  $parent_name = ("" != $dept["parent_name"]) ? $dept["parent_name"] : "ROOT";
                  echo "
		        <tr>
                  <th scope=\"row\">{$index}</th>
                  <td>{$dept_full_name}</td>
                  <td>{$dept_name}</td>
                  <td>{$parent_name}</td>
                </tr>";
              }
                ?>
              </tbody>
            </table>
		</div>
		<div>
			<!-- <a class="btn btn-success" href="<?php echo $this->baseUrl("/college/colman/add")?>"><i class="glyphicon glyphicon-plus"></i><b>添加</b></a> -->
		</div>
	</div>
</div>