<div id="view-content">
	<h3><b><?php echo $this->scholarship_condition["scholarship_name"];?></b>条件修改</h3>
	<div class="col-md-12">
		<form role="form" class="form form-horizontal" method="post" action="<?php echo $this->baseUrl("/bursary/condition/edit-ok");?>">
			<div class="form-group">
				<label for="college_name">奖学金名称</label>
				<input type="text" class="form-control" value="<?php echo $this->scholarship_condition["scholarship_name"];?>" readonly>
			</div>
			<div class="form-group">
				<label for="college_name">奖学金等级</label>
				<input type="text" class="form-control" value="<?php echo $this->scholarship_condition["scholarship_type_name"];?>" readonly>
			</div>
			<div class="form-group">
				<p><b>条件表达式</b></p>
				<div class="form-inline">
					<div class="col-md-12">
    					<select class="form-control col-md-4" name="key" >
    					<option value="course_grade" <?php if ("course_grade" == $this->scholarship_condition["key"]) echo " selected";?>>成绩排名</option>
    					<option value="escape_time" <?php if ("escape_time" == $this->scholarship_condition["key"]) echo " selected";?>>逃课次数</option>
    					<option value="course_no_passed" <?php if ("course_no_passed" == $this->scholarship_condition["key"]) echo " selected";?>>挂科门数</option>
    					<option value="discipline" <?php if ("discipline" == $this->scholarship_condition["key"]) echo " selected";?>>不良记录</option>
    					</select>
    					<select class="form-control col-md-4" name="symbol" >
        					<option value="&lt;"<?php if ("<" == $this->scholarship_condition["symbol"]) echo " selected";?>>&lt;</option>
        					<option value="&lt;="<?php if ("<=" == $this->scholarship_condition["symbol"]) echo " selected";?>>&lt;=</option>
        					<option value="&gt;"<?php if (">" == $this->scholarship_condition["symbol"]) echo " selected";?>>&gt;</option>
        					<option value="&gt;="<?php if (">=" == $this->scholarship_condition["symbol"]) echo " selected";?>>&gt;=</option>
        					<option value="="<?php if ("=" == $this->scholarship_condition["symbol"]) echo " selected";?>>=</option>
    					</select>
    					<input class="form-control col-md-4" name="value" type="text" placeholder="请输入条件值" value="<?php echo  $this->scholarship_condition["value"];?>" required>
    				</div>
					<p class="help-block">参考写法：成绩排名 &lt 15 (15%内); 逃课次数  &lt 1 (不能逃课); 挂科门数 &lt 1(不能挂科); 不良记录 &lt 1（不能有不良记录）</p>
				</div>
			</div>
			<input type="hidden" name="condition_id" value="<?php echo $this->scholarship_condition["condition_id"];?>">
			<input type="hidden" name="scholarship_id" value="<?php echo $this->scholarship_condition["scholarship_id"];?>">
			<button type="submit" class="btn btn-primary">提交</button>
		</form>
	</div>
</div>