<div id="view-content">
	<h3><b><?php echo $this->scholarshipinfo["scholarship_name"];?></b>申请条件</h3>
	<div class="col-md-12">
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>序号</th>
                  <th>条件表达式</th>
                  <th>编辑</th>
                </tr>
              </thead>
              <tbody>
              <?php 
              foreach ($this->condition_list as $index=>$condition) {
                  switch ($condition['key']) {
                      case "course_grade": $condition['key'] = "成绩排名"; break;
                      case "escape_time": $condition['key'] = "逃课次数"; break;
                      case "course_no_passed": $condition['key'] = "挂科门数"; break;
                      case "discipline": $condition['key'] = "不良记录"; break;
                  }
                  $expression = $condition['key'] . $condition['symbol'] .$condition['value'];
                  $index ++;
                  echo 
                    "<tr>
                      <td>{$index}</td>
                      <td>{$expression}</td>
                       <td><a href=\"{$this->baseUrl("/bursary/condition/edit/id/" . $condition["condition_id"])}\" class=\"btn btn-warning btn-xs\"><i class=\"glyphicon glyphicon-edit\"></i>修改</a><a href=\"javascript:delete_confirm('{$condition["condition_id"]}');\" class=\"btn btn-danger btn-xs\"><i class=\"glyphicon glyphicon-trash\"></i>删除</a></td>
                    </tr>";
              }
                ?>
              </tbody>
            </table>
		</div>
		<div>
		 <a class="btn btn-success" href="<?php echo $this->baseUrl("/bursary/condition/add/id/" . $this->scholarshipinfo["scholarship_id"])?>"><i class="glyphicon glyphicon-plus"></i><b>添加</b></a>
		</div>
	</div>
</div>

<?php 
$this->headLink()->appendStylesheet($this->baseUrl("/plugins/bootstrap-dialog/dist/css/bootstrap-dialog.min.css"));
$this->headScript()->appendFile($this->baseUrl("/plugins/bootstrap-dialog/dist/js/bootstrap-dialog.min.js"));
$this->headScript()->appendScript("
    
    function delete_confirm(code)
    {
        BootstrapDialog.show({
    		title: '警告',
    	    message: '<h3>删除不可撤销</h3>',
    	    type: BootstrapDialog.TYPE_WARNING,
    	    closable: true,
    	    closeByBackdrop: false,
    	    closeByKeyboard: false,
    	    buttons: [{
                label: '确定',
    	        cssClass: 'btn-warning',
    	        action: function(dialogRef){
                    window.location.href = '" . $this->baseUrl('/bursary/condition/del/id/') . "'+code; 
    	        }
    	    },{
    	        label: '取消',
    	        cssClass: 'btn-default',
    	        action: function(dialogRef){
    	            dialogRef.close();
    	        }
    	    }]
	    });
    }

", $type = 'text/javascript');

?>
