<div id="view-content">
	<div class="col-md-12">
	<h3>系统资源访问控制列表</h3>
		<div class="table-responsive">
    		<table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th>序号</th>
                  <th>用户角色名</th>
                  <th>可访问资源</th>
                  <th>资源操作</th>
                </tr>
              </thead>
              <tbody>
              <?php 
              foreach ($this->privilege as $index=>$privilege) {
                  $privilege_html = "";
                  if (count($privilege["privilege"]) > 0) {
                      foreach ($privilege["privilege"] as $item) {
                          $privilege_html .= "<span class=\"label label-default\">" . $item["resource_name"] . "-" . $item["action_name"] . "</span>";
                      }
                      
                  }
//                   $action_list_html .= "<a href=\"" . $this->baseUrl("/user/resource/action-add/resource_id/" . $resource["resource_id"]) . "\" class=\"btn btn-success btn-xs\"><i class=\"glyphicon glyphicon-plus\"></i>添加方法</a>";
                  $index ++;
                  echo 
                    "<tr>
                      <th scope=\"row\">{$index}</th>
                      <td>{$privilege["type_name"]}</td>
                      <td>{$privilege_html}</td>
                      <td>
                        <a href=\"{$this->baseUrl("/user/acl/edit/type_code/" . $privilege["type_code"])}\" class=\"btn btn-warning btn-xs\"><i class=\"glyphicon glyphicon-edit\"></i>修改</a>
                      </td>
                    </tr>";
              }
                ?>
              </tbody>
            </table>
		</div>
		<div>
		 <a class="btn btn-success" href="<?php echo $this->baseUrl("/user/resource/resource-add")?>"><i class="glyphicon glyphicon-plus"></i><b>添加资源</b></a>
		</div>
	</div>
</div>

<?php 
$this->headLink()->appendStylesheet($this->baseUrl("/plugins/bootstrap-dialog/dist/css/bootstrap-dialog.min.css"));
$this->headScript()->appendFile($this->baseUrl("/plugins/bootstrap-dialog/dist/js/bootstrap-dialog.min.js"));
$this->headScript()->appendFile($this->baseUrl("/static/js/public.js"));
$this->headScript()->appendScript("
    
    var Public = new PublicClass();
    function delete_confirm(resource_id)
    {
        BootstrapDialog.show({
    		title: '警告',
    	    message: '<h3>删除不可撤销，并确保该资源没有被分配出去</h3>',
    	    type: BootstrapDialog.TYPE_WARNING,
    	    closable: true,
    	    closeByBackdrop: false,
    	    closeByKeyboard: false,
    	    buttons: [{
                label: '确定',
    	        cssClass: 'btn-warning',
    	        action: function(dialogRef){
                    window.location.href = '" . $this->baseUrl('/user/resource/resource-del/resource_id/') . "'+resource_id;
    	        }
    	    },{
    	        label: '取消',
    	        cssClass: 'btn-default',
    	        action: function(dialogRef){
    	            dialogRef.close();
    	        }
    	    }]
	    });
    }

", $type = 'text/javascript');

?>
