<div id="view-content">
	<h3><b><?php echo $this->scholarship_flow["scholarship_name"];?></b>申请发放流程修改</h3>
	<div class="col-md-12">
		<form role="form" class="form form-horizontal" method="post" action="<?php echo $this->baseUrl("/bursary/flow/edit-ok");?>">
			<div class="form-group">
				<label for="college_name">奖学金名称</label>
				<input type="text" class="form-control" value="<?php echo $this->scholarship_flow["scholarship_name"];?>" readonly>
			</div>
			<div class="form-group">
				<label for="college_name">奖学金等级</label>
				<input type="text" class="form-control" value="<?php echo $this->scholarship_flow["scholarship_type_name"];?>" readonly>
			</div>
			<div class="form-group">
				<label for="dept_code">上级流程</label>
				<label class="checkbox-inline">
    			    <input type="checkbox" id="flow_id_0" name="parent_id[]" value="<?php echo $this->scholarshipinfo["scholarship_id"];?>">起始
    			    </label>
				 <?php 
    			$flow_list = $this->flow_list;
    			$parent_code = null;
    			$len = count($flow_list);
    			for ($i = 0; $i < $len; $i ++) {
    			    $checked = ($flow_list[$i]['flow_id'] == $this->scholarship_flow["parent_id"]) ? "checked" : "";
    			    $j = $i + 1;
    			    //     			    echo "<option value=\"{$flow_list[$i]['flow_id']}\">" . $flow_list[$i]["flow_name"] . "</option>";
    			    echo "<label class=\"checkbox-inline\">
    			    <input type=\"checkbox\" id=\"flow_id_{$j}\" name=\"parent_id[]\" value=\"{$flow_list[$i]['flow_id']}\" {$checked}>{$flow_list[$i]["flow_name"]}
    			    </label>";
    			}

    			?>
			</div>

			<div class="form-group">
				<label for="college_name">当前流程名</label>
				<input type="text" class="form-control" name="flow_name" value="<?php echo $this->scholarship_flow["flow_name"];?>" required>
			</div>
			<div class="form-group">
				<label for="college_name">审核对象</label>
				<input type="text" class="form-control" name="check_role_id" value="<?php echo $this->scholarship_flow["check_role_id"];?>" required>
			</div>
			<input type="hidden" name="scholarship_id" value="<?php echo $this->scholarship_flow["scholarship_id"];?>">
			<input type="hidden" name="flow_id" value="<?php echo $this->scholarship_flow["flow_id"];?>">
			<button type="submit" class="btn btn-primary">提交</button>
		</form>
	</div>
</div>
