
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

	<?php echo $this->headTitle();?>
    <!-- Bootstrap core CSS -->
    <link href="<?php echo $this->baseUrl("/plugins/bootstrap/css/bootstrap.min.css");?>" rel="stylesheet">
    <?php echo $this->headLink();?>
	<!-- <link href="<?php echo $this->baseUrl("/plugins/DataTables/jquery.dataTables.css");?>" rel="stylesheet">
	<link href="<?php echo $this->baseUrl("/plugins/DataTables/extensions/ColVis/css/dataTables.colVis.css");?>" rel="stylesheet">
	<link href="<?php echo $this->baseUrl("/plugins/DataTables/extensions/TableTools/css/dataTables.tableTools.css");?>" rel="stylesheet">
	 -->

    <!-- Custom styles for this template -->
        <link href="<?php echo $this->baseUrl("/static/css/style.css");?>" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">奖学金申报</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <?php 
            $auth = Zend_Auth::getInstance();
            $identity = $auth->getIdentity();
            if (isset($identity->user_id)) {
            ?>
            <li role="presentation" class="dropdown">
                <a id="drop1" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <i class="glyphicon glyphicon-user"></i><?php echo $identity->user_id?>
                  <span class="caret"></span>
                </a>
                <ul id="menu1" class="dropdown-menu" aria-labelledby="drop1">
                  <li><a href="<?php echo $this->baseUrl("/default/account/reset");?>">修改密码</a></li>
                  <li><a href="<?php echo $this->baseUrl("/default/account/logout");?>">注销</a></li>
                </ul>
           </li>
			<?php }?>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li><a href="<?php echo $this->baseUrl("/default/bursary/index");?>">所有奖学金 <span class="sr-only">(current)</span></a></li>
            <li><a href="<?php echo $this->baseUrl("/default/bursary/my");?>">我的奖学金</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="<?php echo $this->baseUrl("/student/type/list");?>">学生类型</a></li>
            <li><a href="<?php echo $this->baseUrl("/student/info/list");?>">学生信息</a></li>
            <li><a href="<?php echo $this->baseUrl("/student/condition/list");?>">资格审查</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="<?php echo $this->baseUrl("/faculty/info/list");?>">教师信息</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="<?php echo $this->baseUrl("/bursary/type/list");?>">奖学金类型</a></li>
            <li><a href="<?php echo $this->baseUrl("/bursary/info/list");?>">奖学金信息</a></li>
            <li><a href="<?php echo $this->baseUrl("/bursary/check/list");?>">奖学金审核</a></li>
            <li><a href="<?php echo $this->baseUrl("/bursary/pay/list");?>">奖学金发放</a></li>
          </ul>
          <ul class="nav nav-sidebar">
          	<li><a href="<?php echo $this->baseUrl("/tuition/info/list");?>">费用管理</a></li>
          	<li><a href="<?php echo $this->baseUrl("/tuition/fee/list");?>">欠费管理</a></li>
            <li><a href="<?php echo $this->baseUrl("/tuition/charging/list");?>">扣费管理</a></li>
            <li><a href="<?php echo $this->baseUrl("/tuition/bank/list");?>">银行卡管理</a></li>
          </ul>
          <ul class="nav nav-sidebar">
          	<li><a href="<?php echo $this->baseUrl("/user/resource/list");?>">资源管理</a></li>
          	<li><a href="<?php echo $this->baseUrl("/user/auth/list");?>">角色管理</a></li>
          	<li><a href="<?php echo $this->baseUrl("/user/resource/acl");?>">访问控制</a></li>
          	<li><a href="<?php echo $this->baseUrl("/user/account/list");?>">用户管理</a></li>
          	<li><a href="<?php echo $this->baseUrl("/user/account/search");?>">密码重置</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <?php echo $this->layout()->content;?>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
	<script src="<?php echo $this->baseUrl("/plugins/jquery/jquery-1.11.2.min.js");?>"></script>
    <script src="<?php echo $this->baseUrl("/plugins/bootstrap/js/bootstrap.min.js");?>"></script>
    <?php echo $this->headScript();?>
   
  </body>
</html>
